namespace SetuShell
{
    [default_interface]
    runtimeclass AppTileViewModel
    {
        AppTileViewModel(String packageName, String name, String iconPath);
        String PackageName { get; };
        String Name { get; };
        String IconPath { get; };
    }
}
